job_type: 'spark'
Configurations:
  - config: 
    -   Environment: 'DEV'
        airflow_run_config:
        - owner: 'airflow2'
          retries: '1'
          retry_delay: minutes=1
        airflow_dag_details:
        - dag_name: 'SPARK_SUBMIT_JOB'
          description: 'sample spark job run'
          task_id: 'spark_submit_task'
          schedule_interval: '@daily'
          start_year: '2018'
          start_month: '04'
          start_day: '15'
        spark_configs:
        - conf: ''
          conn_id: ''
          files: ''
          py_files: ''
          jars: 'spark.jar'
          driver_class_path: ''
          java_class: 'org.apache.spark.examples.SparkPi'
          packages: ''
          exclude_packages: ''
          repositories: ''
          total_executor_cores: ''
          executor_cores: ''
          executor_memory: ''
          driver_memory: ''
          keytab: ''
          principal: ''
          name: 'Py Spark Jar'
          num_executors: ''
          application_args: '["10","--with-spaces", "args should not embedded spaces"]'
          env_vars: ''
          verbose: ''
          spark_binary: ''
  - config: 
    -   Environment: 'QA'
        airflow_run_config:
        - owner: 'airflow'
          retries: '1'
          retry_delay: minutes=1
        airflow_dag_details:
        - dag_name: 'SPARK_SUBMIT_JOB'
          description: 'sample spark job run'
          task_id: 'spark_submit_task'
          schedule_interval: '@daily'
          start_year: '2018'
          start_month: '04'
          start_day: '15'
        spark_configs:
        spark_configs:
        - conf: ''
          conn_id: ''
          files: ''
          py_files: ''
          jars: ''
          driver_class_path: ''
          java_class: 'org.apache.spark.examples.SparkPi'
          packages: ''
          exclude_packages: ''
          repositories: ''
          total_executor_cores: ''
          executor_cores: ''
          executor_memory: ''
          driver_memory: ''
          keytab: ''
          principal: ''
          name: 'Py Spark Jar'
          num_executors: ''
          application_args: '["10","--with-spaces", "args should not embedded spaces"]'
          env_vars: ''
          verbose: ''
          spark_binary: ''